use empresa;


-- CREAMOS NUESTRAS TABLAS 

CREATE TABLE clientes(
DNI VARCHAR(11) NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
DIRECCION VARCHAR(150) ,
BARRIO VARCHAR(50) ,
CIUDAD VARCHAR (50) ,
ESTADO VARCHAR(20),
CP VARCHAR(10),
FECHA_NACIMIENTO DATE ,
EDAD SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUMEN_COMPRA FLOAT,
PRIMERA_COMPRA BIT,
PRIMARY KEY(DNI)

);

CREATE TABLE `vendedores` (
  `MATRICULA` varchar(11) NOT NULL,
  `NOMBRE` varchar(100) ,
  `BARRIO` varchar(50) ,
  `COMISION` FLOAT ,
  `FECHA_ADMISION`DATE ,
  `VACASIONES` BIT(1),
  PRIMARY KEY (`MATRICULA`)
);


CREATE TABLE `productos` (
  `CODIGO` varchar(20) NOT NULL,
  `DESCRIPCION` varchar(100) ,
  `SABOR` varchar(50) ,
  `TAMAÑO` varchar(50),
  `ENVASE`varchar(50) ,
  `PRECIO` FLOAT,
  PRIMARY KEY (`CODIGO`)
);

CREATE TABLE venta (
NUMERO VARCHAR(50) NOT NULL ,
FECHA_VENTA DATE,
DNI VARCHAR(11),
MATRICULA VARCHAR(20),
IMPUESTO FLOAT NOT NULL
VENTA_DNI VARCHAR(50)
)